apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 1                      # кількість екземплярів Pod, що буде створено цим Deployment
  selector:
    matchLabels:
      app: storage                # селектор по якому Deployment зв'язаний з Pod
  template:
    metadata:
      labels:
        app: storage               # мітка Pod по якому вона буде зв'язана з Deployment та Service
    spec:
      initContainers:
        - name: run-migrations
          image: storage-migrations:10
          command: [ "mvn", "flyway:migrate" ] # CLI команда запуску міграцій, де $(POSTGRESQL_URL) і $(VERSION) змінні середовища
          env:
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres:5432/demo"


      containers:
        - image: storage:10      # образ Docker
          imagePullPolicy: Never   # вказує k8s, що образ не потрібно завантажувати (варто використовувати лише для випадків, коли образи локальні)
          name: storage           # ім'я контейнеру
          ports:
            - containerPort: 3001  # порт по якому можна звертатись до поди
          envFrom:
            - configMapRef:
                name: storage-config
            - secretRef:
                name: storage-secret
