postgresql:
  fullnameOverride: postgresql # використовується як хост
  postgresqlDatabase: "demo"
  postgresqlUsername: "demo"
  postgresqlPassword: "demo"
  postgresqlPostgresPassword: "demo"
  persistence:
    size: 5Gi
    mountPath: /var/lib/postgresql/data