replicaCount: 1

service:
  ports:
    - name: http
      port: 8080
      containerPort: 3003

ingress:
  path: /api/order
  port: 8080

selector:
  app: order

image:
  author: veronikashukhman
  name: order2
  tag: 25

config:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres
  DATABASE_URL: jdbc:postgresql://postgres:5432/demo
  AMQP_URL: amqp://user:user@rabbitmq:5672

secret:
  #  JWT_SECRET: d7b79c83a74b1bfed52d80df15558874
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo
#  POSTGRES_USER: "ZGVtbw=="
#  POSTGRES_PASSWORD: "ZGVtbw=="

migrations:
  image:
    name: order_migrations
    tag: 25
  config:
    POSTGRES_DB: demo
    POSTGRES_USER: demo
    POSTGRES_PASSWORD: demo
    DATABASE_URL: "jdbc:postgresql://postgres:5432/demo"

virtual:
  timeout: 5s
  retries:
    attempts: 3
    retryOn: 5xx
    perTryTimeout: 5s

destination:
  consecutive5xxErrors: 5
  interval: 10s
  baseEjectionTime: 30s
  maxEjectionPercent: 80